name: Build and Push to GHCR - 150_docker_fastapi_01

on:
  push:
    paths:
      - 150_docker_fastapi_01/**

  workflow_dispatch:


env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: ashwin-francis/150_docker_fastapi_01
  IMAGE_TAG: 0.0.${{ github.run_number }}

jobs:

  build-push-docker:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log into registery ${{ env.REGISTRY }}
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract Docker Metadata
      id: meta
      uses: docker/metadata-action@v1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
    - name: Build and Push Docker Image
      id: build-and-push
      uses: docker/build-push-action@v2
      with:
        context: 50_docker_python01
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        labels: ${{ steps.meta.outputs.labels }}